# Generated by Django 3.2.15 on 2022-08-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipes_ingredients'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='pub_date',
        ),
    ]
